#!/bin/bash
set -x -v -e
# if line above NOT THERE then the REST below is not seen

echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
export GITHUB_WORKSPACE_POSIX="$(cygpath "${GITHUB_WORKSPACE}")"
echo "GITHUB_WORKSPACE_POSIX: ${GITHUB_WORKSPACE_POSIX}"

echo "GREETING_FROM_CALLING_SHELL: ${GREETING_FROM_CALLING_SHELL}"

export GREETING_FROM_CHILD_SHELL="GREETING_FROM_CHILD_SHELL Hello"

echo "GREETING=GREETING Hello" >> ${GITHUB_ENV}
echo "GREETING_OUTPUT=GREETING_OUTPUT Hello" >> ${GITHUB_OUTPUT}
echo "GREETING_OUTPUT_BETWEEN_JOBS=GREETING_OUTPUT_BETWEEN_JOBS Hello" >> ${GITHUB_OUTPUT}
