#!/usr/bin/env bash

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
set -x -v -e

uname -a

mirrordir="`echo "HELLO" | sed -e "s:E:U:g" | grep U  `"
echo $mirrordir

cat ./out.txt | awk '{print $1}'

if [ "1" == "1" ]
then
  echo ONE
fi

export | grep TEMP || true
