name: arrayFromGitOutput

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: action
      shell: powershell
      run: |
        ${env:RESULT}   = $(& "C:\Program Files\Git\bin\git.exe")
        Write-Output ${env:RESULT}
