name: arrayFromGitOutput

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: action
      shell: powershell
      run: |
       # powershell /? (see the example at the bottom)
       # $command = 'dir "c:\program files" '
       $command = 'git ls-remote --tags "https://github.com/postgres/postgres.git"'
       $bytes = [System.Text.Encoding]::Unicode.GetBytes($command)
       $encodedCommand = [Convert]::ToBase64String($bytes)
       powershell.exe -encodedCommand $encodedCommand | Out-File -FilePath "C:\output.txt"
       $fileContent = Get-Content -Path "C:\output.txt"
       foreach ($line in $fileContent) { Write-Output $line.substring(51) }
      
   
