name: arrayFromGitOutput

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: action
      shell: powershell
      run: |
        ${env:RESULT}   = $(Start-Process -FilePath "$env:ProgramFiles\Git\bin\git.exe" -ArgumentList "ls-remote", "--tags", "-c", '"https://github.com/postgres/postgres.git"')
        Write-Output ${env:RESULT}
