name: arrayFromGitOutput

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: action
      shell: powershell
      run: |
       $command = 'dir "c:\program files" '
       $bytes = [System.Text.Encoding]::Unicode.GetBytes($command)
       $encodedCommand = [Convert]::ToBase64String($bytes)
       powershell.exe -encodedCommand $encodedCommand | Out-File -FilePath "C:\output.txt"
       # Get-Content -Path "C:\output.txt"
       # Write-Output ${env:RESULT}
