name: plr CI NIX

on: [push, pull_request]

jobs:

  information_env:
    name: Knowledge About env
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context global data
        run:   export
        shell: bash

  information_github:
    name: Knowledge About github
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context global data
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  information_ubuntu:
    name: Knowledge About runner ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Dump runner context global data
        run:   echo "$RUNNER_CONTEXT"
        shell: bash
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}

  build_NIX:

    name: ${{ matrix.os }} ${{ matrix.pg }} ${{ matrix.Platform}} ${{ matrix.Configuration }} ${{ matrix.rversion }} ${{ matrix.Compiler}}
    runs-on: ${{ matrix.os }}
    strategy:
      # Disable fail-fast as we want results from all even if one fails
      fail-fast: false
      matrix:
        include:

          - pg: repository
            configuration: Debug
            Platform: x64
            os: windows-latest
            rversion: 4.2.3
            compiler: mingw64
            asset_extension: .7z

          - pg: repository
            configuration: Debug
            Platform: x64
            os: windows-latest
            rversion: 4.3.1
            compiler: mingw64
            asset_extension: .7z

    steps:

      - name: Windows System
        if: matrix.os == 'windows-latest'
        run: |
          systeminfo

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Variables Test 1
        run: |
          Set-PSDebug -Trace 2
          echo "${{ matrix.os }}"
          echo "${{ sender.login }}"
          echo "${env:windir}"
          echo "${{ env.GITHUB_WORKSPACE }}"
          echo "${env:GITHUB_WORKSPACE}"
          ${env:DERIVED} = "${env:GITHUB_WORKSPACE} ${{ matrix.os }} ${env:windir} ${{ sender.login }}"
          echo "${env:DERIVED}"
          echo ${{ env.DERIVED }}

      - name: shell DERIVED detected in further step 
        run: |
          echo shell DERIVED
          echo ${env:DERIVED}

      - name: env DERIVED detected in further step
        run: |
          echo env.DERIVED
          echo ${{ env.DERIVED }}

      - name: env.windir detected
        if: ${{ matrix.os == 'windows-latest' &&  env.windir != '' }}
        run: |
          echo if expression - env.windir detected

      - name: env.USER_SHA detected
        if: ${{ matrix.os == 'windows-latest' &&  env.USER_SHA != '' }}
        run: |
          echo if expression - env.USER_SHA detected

#       - name: shell USER_SHA detected # Unexpected symbol: '${env:USER_SHA}'
#         if: ${{ matrix.os == 'windows-latest' &&  ${env:USER_SHA} != '' }}
#         run: |
#           echo if expression - shell USER_SHA detected
# 
#       - name: shell DERIVED detected # Unexpected symbol: '${env:DERIVED}'
#         if: ${{ matrix.os == 'windows-latest' &&  ${env:DERIVED} != '' }}
#         run: |
#           echo if expression - shell DERIVED detected
