name: CI

on: [push, pull_request]

# THIS IS BASED OFF OF
# https://github.com/grimme-lab/blas-interface/blob/f31a8b67fcd36771ee3ee04f63b7ff38e81e17f9/.github/workflows/build.yml

jobs:
  build:
    name: ${{ matrix.MSYSTEM }} ${{ matrix.shell }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

        - os: windows-latest

    steps:

    - name: Prepare to Download Files from Github
      run: |
        git config --global core.autocrlf input
        git config --global advice.detachedHead false

    - name: Checkout code
      uses: actions/checkout@v2

    # https://github.com/java-native-access/jna/blob/6c0fb985284982d2a2f70c07877f3baf16bc5421/native/libffi/.github/workflows/build.yml#L217
    - name: Set up Cygwin egor-tensin/setup-cygwin@v3 x64
      uses: egor-tensin/setup-cygwin@v3
      with:
        platform: x64
        packages: wget

    - name: Run Cygwin egor-tensin/setup-cygwin@v3 x64
      env:
        SHELLOPTS: igncr
      shell: C:\tools\cygwin\bin\bash.exe '{0}'
      run: |
        uname -a
        export | grep MSYSTEM

