name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.MSYSTEM }} ${{ matrix.shellEnv }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

        - os: windows-latest
          shellEnv: sh
          Platform: x86

    defaults:
      run:
        shell: ${{ matrix.shellEnv || 'bash' }}

    steps:

    - name: Prepare to Download Files from Github
      run: |
        git config --global core.autocrlf input
        git config --global advice.detachedHead false

    - name: Checkout code
      uses: actions/checkout@v2

    # https://github.com/cygwin/cygwin-install-action/tree/006ad0b0946ca6d0a3ea2d4437677fa767392401
    - name: Set up Cygwin cygwin/cygwin-install-action@v4 x86
      uses: cygwin/cygwin-install-action@v4
      with:
        # x86 or x86_64
        platform: ${{ matrix.Platform  == 'x64' && 'x86_64' || 'x86' }}
        packages: mksh
        add-to-path: false

    - name: Run Cygwin cygwin/cygwin-install-action@v4 x86 VER cmd
      env:
        SHELLOPTS: igncr
        CHERE_INVOKING: 1
      shell: cmd
      run: |
        set PATH=C:\cygwin\bin
        bash mini

    # help from
    # https://github.com/egor-tensin/setup-cygwin/tree/v3.0.1
    - name: Run Cygwin cygwin/cygwin-install-action@v4 x86 VER call
      env:
        SHELLOPTS: igncr
        CHERE_INVOKING: 1
      shell:  C:\Cygwin\bin\bash.exe --login '{0}'
      run: |
        export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
        set -x -v -e
        uname -a
        echo "Present Working Directory: $(pwd)"
        export | grep TEMP
        bash mini

    - name: Run Cygwin cygwin/cygwin-install-action@v4 x86 bash
      env:
        SHELLOPTS: igncr
        CHERE_INVOKING: 1
      shell: bash
      run: |
        export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
        set -x -v -e
        uname -a
        echo "Present Working Directory: $(pwd)"
        export | grep TEMP
        bash mini

    - name: Run Cygwin cygwin/cygwin-install-action@v4 x86 shellEnv
      env:
        SHELLOPTS: igncr
        CHERE_INVOKING: 1
      run: |
        export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
        echo "SHELL: ${SHELL}"
        set -x -v -e
        uname -a
        which bash
        which ksh || true
        echo "Present Working Directory: $(pwd)"
        export | grep TEMP
        bash mini


