name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.MSYSTEM }} ${{ matrix.shell }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

        - os: windows-latest

    steps:

    - name: Prepare to Download Files from Github
      run: |
        git config --global core.autocrlf input
        git config --global advice.detachedHead false

    - name: Checkout code
      uses: actions/checkout@v2

    # https://github.com/cygwin/cygwin-install-action/tree/006ad0b0946ca6d0a3ea2d4437677fa767392401
    - name: Set up Cygwin cygwin/cygwin-install-action@v4 x86
      uses: cygwin/cygwin-install-action@v4
      with:
        # x86 or x86_64
        platform: x86
        packages: wget
        add-to-path: false

    - name: Run Cygwin cygwin/cygwin-install-action@v4 x86 VER cmd
      env:
        SHELLOPTS: igncr
      shell: cmd
      CHERE_INVOKING: 1
      run: |
        set PATH=C:\cygwin\bin
        bash mini


