name: CI

on: [push, pull_request]

# THIS IS BASED OFF OF
# https://github.com/grimme-lab/blas-interface/blob/f31a8b67fcd36771ee3ee04f63b7ff38e81e17f9/.github/workflows/build.yml

env:
  BUILD_DIR: _build

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-latest
          feature: a
          shell: msys2 {0}
        - os: windows-latest

    defaults:
      run:
        shell: ${{ matrix.shell || 'powershell' }}
    steps:
    - name: MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false

    - name: DO default
      run: |
        echo "matrix shell: ${{ matrix.shell }}"
        uname -a

    - name: DO powershell
      shell: powershell
      run: |
        echo "matrix shell: ${{ matrix.shell }}"
        msys2 -c 'uname -a'

    - name: DO cmd
      shell: cmd
      run: |
        echo "matrix shell: ${{ matrix.shell }}"
        msys2 -c 'uname -a'

    - name: DO powershell ver
      shell: powershell
      run: |
         Get-CIMInstance -Class Win32_Processor | Select-Object -Property Name

    - name: DO cmd ver
      shell: cmd
      run: |
        systeminfo | findstr /B "/C:OS Name" /B "/C:OS Version"


