name: CI

on: [push, pull_request]

# THIS IS BASED OFF OF
# https://github.com/grimme-lab/blas-interface/blob/f31a8b67fcd36771ee3ee04f63b7ff38e81e17f9/.github/workflows/build.yml

jobs:
  build: 
    name: ${{ matrix.MSYSTEM }} ${{ matrix.shell }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

        - os: windows-latest
          MSYSTEM: UCRT
          shell: msys2 {0}

        - os: windows-latest
          MSYSTEM: MINGW32
          shell: msys2 {0}

        - os: windows-latest
          shell: powershell
          MSYSTEM: ''
          OSYSTEM: CLANG32

    # possible STYLE - I am better off naming my shells explicitly
    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
    - name: MSYS2
      # continue-on-error: true
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: false

    - name: Set Variables
      continue-on-error: true
      shell: powershell
      run: |
        function Set-EnvVar {param($X)     Add-Content -Path ${env:GITHUB_ENV} -Value "$X"}
        ${env:do} = "true"
        Set-EnvVar "do=${env:do}"

    - name: DO powershell version
      continue-on-error: true
      shell: powershell
      run: |
        ${env:Location} = Get-Location
        echo "Location: ${env:Location}"
        echo "matrix shell: ${{ matrix.shell }}"
        Get-CIMInstance -Class Win32_Processor | Select-Object -Property Name
        ${env:MSYSTEM} = "UCRT64"
        # DOES NOT COMPLAINT THAT CAN NOT FIND THE FILE.  NO OUTPUT IS PRODUCED
        # ${env:GITHUB_WORKSPACE}/msys2--setup-msys.sh
        msys2 -c 'set -x -v -e;uname -a;export | grep MINGW;export | grep MSYSTEM; echo "Present Working Directory $(pwd)"' 
        #
        # /usr/bin/bash: line 1: /msys2--setup-msys.sh: No such file or directory
        # msys2 -c 'set -x -v -e;${env:GITHUB_WORKSPACE}/msys2--setup-msys.sh >> $GITHUB_OUTPUT'
        #
        # /usr/bin/bash: msys2--setup-msys.sh: No such file or directory
        # msys2 -l msys2--setup-msys.sh

        # /usr/bin/bash: D:\a\githubactionstest\githubactionstest/msys2--setup-msys.sh: No such file or directory
        # msys2 -l ${env:GITHUB_WORKSPACE}/msys2--setup-msys.sh

        # /usr/bin/bash: D:\a\githubactionstest\githubactionstest\msys2--setup-msys.sh: No such file or directory
        #msys2 -l ${env:GITHUB_WORKSPACE}\msys2--setup-msys.sh

        # /usr/bin/bash: D:\a\githubactionstest\githubactionstest\msys2--setup-msys.sh: No such file or directory
        # bash -l ${env:GITHUB_WORKSPACE}\msys2--setup-msys.sh
        Get-ChildItem
        #
        # unexected token - ${env:GITHUB_WORKSPACE}\msys2--setup-msys.sh

    - name: DO cmd verson
      continue-on-error: true
      shell: cmd
      run: |
        echo on
        echo Current Working Directory - %CD%
        echo "matrix shell: ${{ matrix.shell }}"
        systeminfo | findstr /B "/C:OS Name" /B "/C:OS Version"
        set MSYSTEM=MINGW32
        dir
        msys2 -c 'set -x -v -e;uname -a'
        rem INGORES EVERYTHING BELOW THIS LINE 
        rem CAN NOT DO PIPING
        %GITHUB_WORKSPACE%\msys2--setup-msys.sh

    - name: DO msys2 {0} version 
      continue-on-error: true
      shell: msys2 {0}
      run: |
        set -x -v -e
        echo "Present Working Directory: $(pwd)"
        echo "matrix shell: ${{ matrix.shell }}"
        uname -a
        echo "MSYSTEM ${MSYSTEM}"
        # CAN NOT DO PIPING

    - name: DO msys2 {0} version MINGW64
      continue-on-error: true
      shell: msys2 {0}
      env:
        MSYSTEM: MINGW64
      run: |
        set -x -v -e
        echo "Present Working Directory: $(pwd)"
        echo "matrix shell: ${{ matrix.shell }}"
        uname -a
        echo "MSYSTEM ${MSYSTEM}"
        export | grep MINGW
        export | grep MSYSTEM
        ls -alrt

    - name: DO msys2 {0} verson ''
      continue-on-error: true
      shell: msys2 {0}
      env:
        MSYSTEM: '' 
        #         IS AVAILABLE - but    '' will FAIL the PIPES
        #         ${{ matrix.OSYSTEM || '' }}
      run: |
        set -x -v -e
        echo "Present Working Directory: $(pwd)"
        echo "matrix shell: ${{ matrix.shell }}"
        uname -a
        echo "MSYSTEM ${MSYSTEM}"
        # CAN NOT DO PIPING

    - name: DO msys2 {0} verson OSYSTEM
      if: ${{  matrix.shell != 'msys2 {0}' }}
      continue-on-error: true
      shell: msys2 {0}
      env:
        MSYSTEM: ${{ matrix.OSYSTEM }}
      run: |
        set -x -v -e
        echo "Present Working Directory: $(pwd)"
        echo "matrix shell: ${{ matrix.shell }}"
        uname -a
        echo "MSYSTEM ${MSYSTEM}"
        # powershell - CAN DO PIPING
        # UCRT msys2 {0} and MINGW32 msys2 {0} CAN NOT DO PIPING
        export | grep MINGW
        export | grep MSYSTEM


    - name: DO msys2 {0} verson OSYSTEM env.do IGNORE ME
      if: ${{  env.do != 'true' }}
      continue-on-error: true
      shell: msys2 {0}
      env:
        MSYSTEM: ${{ matrix.OSYSTEM }}
      run: |
        echo I SHOULD HAVE BEEN IGNORED

