name: CI

on: [push, pull_request]

# THIS IS BASED OFF OF
# https://github.com/grimme-lab/blas-interface/blob/f31a8b67fcd36771ee3ee04f63b7ff38e81e17f9/.github/workflows/build.yml

env:
  BUILD_DIR: _build

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

        - os: windows-latest
          MSYSTEM: UCRT
          shell: msys2 {0}

        - os: windows-latest
          MSYSTEM: MINGW32
          shell: msys2 {0}

        - os: windows-latest
          shell: powershell
          msystem: ''

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
    - name: MSYS2
      continue-on-error: true
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: false

    - name: DO powershell version
      continue-on-error: true
      shell: powershell
      run: |
        echo "matrix shell: ${{ matrix.shell }}"
        Get-CIMInstance -Class Win32_Processor | Select-Object -Property Name
        msys2 -c 'uname -a; echo MSYSTEM ${MSYSTEM}'

    - name: DO cmd verson
      continue-on-error: true
      shell: cmd
      run: |
        echo "matrix shell: ${{ matrix.shell }}"
        systeminfo | findstr /B "/C:OS Name" /B "/C:OS Version"
        msys2 -c 'uname -a; echo MSYSTEM ${MSYSTEM}'

    - name: DO msys2 {0} verson
      continue-on-error: true
      shell: msys2 {0}
      run: |
        echo "matrix shell: ${{ matrix.shell }}"
        uname -a
        echo "MSYSTEM ${MSYSTEM}"
