name: bashfile_write_to_GITHUB_ENV name
run-name: bashfile_write_to_GITHUB_ENV run-name

on:
   push:
   pull_request:
   workflow_dispatch:

env:
  BUILD_GREETING: "BUILD_GREETING Hello"

jobs:
  job1: 
    name: job1 ${{ matrix.os }} ${{ matrix.compilerEnv }} ${{ matrix.shellEnv }}
    env:
      JOB_GREETING: "JOB_GREETING Hello"
    runs-on: ${{ matrix.os }}
    outputs:
      GREETING_OUTPUT_BETWEEN_JOBS: ${{ steps.job1_Run_MSYS2_1.outputs.GREETING_OUTPUT_BETWEEN_JOBS }}
    strategy:
      fail-fast: false
      matrix:
        include:

        - os: windows-2025-vs2026
          compilerEnv: UCRT64
          shellEnv: msys2 {0}

        - os: windows-2022
          compilerEnv: UCRT64
          shellEnv: msys2 {0}

    defaults:
      run:
        shell: ${{ matrix.shellEnv || 'bash' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: job1 Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.compilerEnv }}
        path-type: strict
        update: true

    - name: job1 Run MSYS2 1
      id: job1_Run_MSYS2_1
      env:
        msystem: ${{ matrix.compilerEnv }}
      run: |
        set -x -v -e
        echo "job1 Run MSYS2 1"
        
        echo "BUILD_GREETING: ${BUILD_GREETING}"
        echo "JOB_GREETING: ${JOB_GREETING}"
        # set it
        export GREETING_FROM_CALLING_SHELL="GREETING_FROM_CALLING_SHELL Hello"
        $(cygpath ${GITHUB_WORKSPACE})/bashfile_write_to_GITHUB_ENV.sh
        # receive it
        echo "GREETING_FROM_CHILD_SHELL: ${GREETING_FROM_CHILD_SHELL}"
        echo "env GREETING: ${{ env.GREETING }}"
        echo "GREETING: ${GREETING}"
        export JOB_GREETING="${JOB_GREETING} from previous step"
        export BUILD_GREETING="${BUILD_GREETING} from previous step"

    - name: job1 Run MSYS2 2
      id: job1_Run_MSYS2_2
      env:
        msystem: ${{ matrix.compilerEnv }}
        GREETING: ${{ env.GREETING }}
        GREETING_OUTPUT: ${{ steps.job1_Run_MSYS2_1.outputs.GREETING_OUTPUT }}
      run: |
        set -x -v -e
        echo "job1 Run MSYS2 2"
        echo "GREETING: ${GREETING}"
        echo "GREETING_OUTPUT ${GREETING_OUTPUT}"
        echo "JOB_GREETING: ${JOB_GREETING}"
        echo "BUILD_GREETING: ${BUILD_GREETING}"
        export BUILD_GREETING="${BUILD_GREETING} from previous job"

  job2:
    name: job2 ${{ matrix.os }} ${{ matrix.compilerEnv }} ${{ matrix.shellEnv }}
    needs: job1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

        - os: windows-2025-vs2026
          compilerEnv: UCRT64
          shellEnv: msys2 {0}

        - os: windows-2022
          compilerEnv: UCRT64
          shellEnv: msys2 {0}

    defaults:
      run:
        shell: ${{ matrix.shellEnv || 'bash' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: job2 Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.compilerEnv }}
        path-type: strict
        update: true

    - name: job2 Run MSYS2 1
      id: job2_Run_MSYS2_1
      env:
        msystem: ${{ matrix.compilerEnv }}
        GREETING_OUTPUT_BETWEEN_JOBS: ${{ needs.job1.outputs.GREETING_OUTPUT_BETWEEN_JOBS }}
      run: |
        set -x -v -e
        echo "job2 Run MSYS2 1"
        echo "GREETING_OUTPUT_BETWEEN_JOBS ${GREETING_OUTPUT_BETWEEN_JOBS}"
        echo "BUILD_GREETING: ${BUILD_GREETING}"
