name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  install:
    name: Needs Tests
    runs-on: ubuntu-latest

    steps:
    - name: Install Step
      run: |
        date > install_date.txt

  build_remus:
    name: Build Remus 
    needs: install

    steps:
    - name: See install artifacts
      run: |
        cat install_date.txt || true
        date > build_remus.txt
        cat build_romulus.txt || true

  build_romulus:
    name: Build Romulus 
    needs: install
    runs-on: ubuntu-latest

    steps:
    - name: See install artifiacts
      run: |
        cat install_date.txt || true
        date > build_romulus.txt
        cat build_remus.txt  || true
