name: riscv64
run-name: riscv64 - ${{ github.event.head_commit.message }}

on: 
   push:
   pull_request: 
   workflow_dispatch:

jobs:

  job_master_ubuntu-24_04-riscv:
    name: PG master ubuntu-24.04-riscv
    runs-on: ubuntu-24.04-riscv
    steps:
      - name: Echo site details
        run: echo building master
 
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Checkout
        run: |
          set -x -v -e

          ls -alrt /usr/share/keyrings/ubuntu-archive-keyring.gpg
          

#         sudo apt-get install -qq --no-install-recommends build-essential ca-certificates curl gcc gfortran libblas-dev libbz2-dev libcairo2-dev libcurl4-openssl-dev libicu-dev libjpeg-dev liblapack-dev liblzma-dev libpcre2-dev libpng-dev libreadline-dev libssl-dev libtiff-dev libx11-dev libxml2-dev libxt-dev zlib1g-dev -y
