name: RISC-V
run-name: RISC-V - ${{ github.event.head_commit.message }}

on: 
   push:
   pull_request: 
   workflow_dispatch:

jobs:


  job_master_ubuntu-24_04-riscv:
    name: PG master ubuntu-24.04-riscv
    runs-on: ubuntu-24.04-riscv
    steps:
      - name: Echo site details
        run: echo building master
 
      - name: Checkout code
        uses: actions/checkout@v6
 
      - name: Checkout
        run: |
          set -x -v -e

          export DEBIAN_FRONTEND=noninteractive
          
########### THIS WORKS
#         # To build PostgreSQL and its C client library (libpq) from source
#         # E Unable to locate package libreadline-dev
#         # libreadline-dev 
#         sudo apt-get install -qq build-essential zlib1g-dev flex bison libssl-dev -y
#         git clone --branch master --depth 1 https://github.com/postgres/postgres.git postgres-src
#         pushd postgres-src
#         git checkout master
#         ./configure --help
#         ./configure --without-icu --without-readline --without-zlib --disable-rpath --enable-depend --without-readline
#         make 
#         sudo make install
#         export PATH=/usr/local/pgsql/bin:$PATH
#         # andre added
#         export PATH=/usr/local/pgsql/lib:${PATH}
#         export LD_LIBRARY_PATH=/usr/local/pgsql/lib:${LD_LIBRARY_PATH}
#         #
#         initdb -D data
#         pg_ctl -D data -l logfile start
#         psql -d postgres -c "SELECT version();"
#         psql -d postgres -c "SELECT current_setting('server_version_num');"
#         popd

          cat /etc/apt/sources.list

          # get these libraries

#         sudo apt-get install -qq --no-install-recommends build-essential ca-certificates curl gcc gfortran libblas-dev libbz2-dev libcairo2-dev libcurl4-openssl-dev libicu-dev libjpeg-dev liblapack-dev liblzma-dev libpcre2-dev libpng-dev libreadline-dev libssl-dev libtiff-dev libx11-dev libxml2-dev libxt-dev zlib1g-dev -y
#         #
#         # https://rstudio.github.io/r-manuals/r-admin/Obtaining-R.html
#         sudo apt-get install -qq subversion -y
#         # r-devel
#         svn checkout https://svn.r-project.org/R/trunk/ r-src
#         pushd r-src
#         ./configure --help
#         ./configure --enable-R-shlib --disable-java --disable-byte-compiled-packages --disable-rpath --without-ICU --without-recommended-packages
#         make
#         sudo make install
#         popd
#         export PATH=/usr/local/bin:$PATH
#         R --version
#         popd
#
#     - name: Script
#       run: |
#         set -x -v -e
#         export PATH=/usr/local/pgsql/bin:$PATH
#         # andre added
#         export PATH=/usr/local/pgsql/lib:${PATH}
#         export LD_LIBRARY_PATH=/usr/local/pgsql/lib:${LD_LIBRARY_PATH}
#         # andre added
#         export PATH=/usr/local/bin:$PATH
#         
#     # UNKNOWN IF THIS WORKS OR NOT ...
#
#         export USE_PGXS=1
#         export PATH=/usr/local/pgsql/bin:$PATH
#         SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
#         # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
#         sudo USE_PGXS=1 PATH=/usr/local/pgsql/bin:$PATH make install
#         make installcheck || (cat regression.diffs && false)
#       env:
#         USE_PGXS: 1
#
#     - name: After Success
#       # success() returns true, when none of the previous steps have failed or been canceled.
#       if: ${{ success() }}
#       # Uploads code coverage to codecov.io
#       run: bash <(curl -s https://codecov.io/bash)
