
on: [push, pull_request]

# GitHub Action Set $GITHUB_ENV Not Saving
# 2022
# https://stackoverflow.com/questions/71333335/github-action-set-github-env-not-saving

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set the value
      id: step_one
      shell: bash
      run: |
        echo "action_state=yellow" >> $GITHUB_ENV
        echo "State is: '${{ env.action_state }}'" # No output since same step

    - name: Use the value
      id: step_two
      shell: bash
      run: |
        echo "State is: '${{ env.action_state }}'" # Output works

    - name: Use the value again 1
      id: step_two1
      run: |
        echo "State is: '${{ env.action_state }}'" # Output works
        
    - name: Use the value again 2
      id: step_two2
      shell: cmd
      run: |
        set action_state=${{ env.action_state }}
        echo "State is: %action_state%"
