
on: [push, pull_request]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Set the value
      id: step_one
      shell: cmd
      run: |
        echo "action_state=yellow" >> variables.bat

    - name: Use the value
      id: step_two
      shell: cmd
      run: |
        call variables.bat
        echo "%action_state%" # This will output 'yellow'