
on: [push, pull_request]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Set the value
      id: step_one
      shell: cmd
      run: |
        echo "set action_state=yellow" >> %GITHUB_ENV%
        echo %GITHUB_ENV%
        type %GITHUB_ENV%

    - name: Use the value
      id: step_two
      shell: cmd
      run: |
        type %GITHUB_ENV%
        echo %GITHUB_ENV%
        echo "${{ env.action_state }}" # This will output 'yellow'