
on: [push]

jobs:

  destroy-PG-on-GA-win-image:
    runs-on: windows-latest

    steps:

    - name: Diplay the default Windows PostgreSQL Server service
      shell: cmd
      run: |
        echo on
        rem list of the human-readable names
        sc query state= all | find "DISPLAY_NAME"
        rem DISPLAY_NAME: postgresql-x64-17 - PostgreSQL Server 17

    - name: Gather facts about the default Windows PostgreSQL Server service
      shell: powershell
      run: |
        function Set-EnvVar {param($X)     Add-Content -Path ${env:GITHUB_ENV} -Value "$X"}

        # Get-Service

        # inheriting
        ${env:Platform} = "x64"
        Set-EnvVar "Platform=${env:Platform}"
        echo "Platform: ${env:Platform}"
        
        ${env:PlatformPGAdj} = "notset"
        ${env:PlatformSVCAdj} = "notset"
        # "C:\Program Files (x86)"
        if ("${env:Platform}" -eq "x86") { ${env:PlatformPGAdj} = " (x86)" } else { ${env:PlatformPGAdj} = "" }
        #  x64 PostgreSQL service names on windows
        if ("${env:Platform}" -eq "x64") { ${env:PlatformSVCAdj} = "-x64"  } else { ${env:PlatformSVCAdj} = "" }

        Set-EnvVar "PlatformPGAdj=${env:PlatformPGAdj}"
        echo "PlatformPGAdj: ${env:PlatformPGAdj}"

        Set-EnvVar "PlatformSVCAdj=${env:PlatformSVCAdj}"
        echo "PlatformSVCAdj: ${env:PlatformSVCAdj}"

        ${env:pgWINServiceNameHostDefault} = "notset"
        ${env:pgWINServiceNameHostDefault} = (Get-Service -ErrorAction SilentlyContinue | where-object {$_.name -like "*postgres*"}).Name
        if ("${env:pgWINServiceNameHostDefault}" -eq "") { ${env:pgWINServiceNameHostDefault} = "none" }
        Set-EnvVar "pgWINServiceNameHostDefault=${env:pgWINServiceNameHostDefault}"
        
        echo "pgWINServiceNameHostDefault: ${env:pgWINServiceNameHostDefault}"

        ${env:pgWINServiceExists} = "notset"
        if("${env:pgWINServiceNameHostDefault}" -eq "none") {${env:pgWINServiceExists} = "false"} else {${env:pgWINServiceExists} = "true"}
        Set-EnvVar "pgWINServiceExists=${env:pgWINServiceExists}"
        
        echo "pgWINServiceExists: ${env:pgWINServiceExists}"

        ${env:pgwinmajor} = "notset"
        if("${env:pgWINServiceExists}" -eq "true") {
          echo "pgWINServiceNameHostDefault: ${env:pgWINServiceNameHostDefault}"
          # 1-30 seconds - can not do after a Start-Service
          Stop-Service  -Name "${env:pgWINServiceNameHostDefault}"
          $matches = @()
          "${env:pgWINServiceNameHostDefault}" -match "(\d+[.]{0,1}\d+$)"
          ${env:pgwinmajor} = $matches[1]
          $matches = @()
        } else {
          ${env:pgwinmajor} = "none"
        }
        Set-EnvVar "pgwinmajor=${env:pgwinmajor}"
        echo "pgwinmajor: ${env:pgwinmajor}"

    - name: Remove the default Windows PostgreSQL Server service (except for the registry)
      if: ${{ env.pgWINServiceExists == 'true' }}
      shell: bash
      run: |
        # echo Deleting Service
        # sc delete "postgresql${PlatformSVCAdj}-${pgwinmajor}"
        echo "Uninstalling Service Software (only if from EDB)"
        # uninstall-postgresql.exe
        export POSTGRES_PATH="$(cygpath "C:\Program Files\\${PlatformPGAdj}\PostgreSQL")"
        echo "POSTGRES_PATH: ${POSTGRES_PATH}"
        export UNINSTALLER_PATH="$(cygpath "${POSTGRES_PATH}\\${pgwinmajor}")"
        echo "UNINSTALLER_PATH: ${UNINSTALLER_PATH}"
        export UNINSTALLER_PATH_FILE="$(cygpath "${UNINSTALLER_PATH}\uninstall-postgresql.exe")"
        echo "UNINSTALLER_PATH_FILE: ${UNINSTALLER_PATH_FILE}"
        echo "Investigating possible potential UNINSTALLER: ${UNINSTALLER_PATH_FILE}"
        if [ -f "${UNINSTALLER_PATH_FILE}" ]
        then
          echo "UNINSTALLER found"
          ls -alrt "${UNINSTALLER_PATH_FILE}"
          "${UNINSTALLER_PATH_FILE}" --mode unattended
          ls -alrt "${UNINSTALLER_PATH}"
        else
          echo "UNINSTALLER not found.  This was not an EDB PostgreSQL database."
        fi
        echo Deleting Files and the Directory
        rm -Rf "$(cygpath "C:\Program Files${PlatformPGAdj}\PostgreSQL")"
 
    - name: Remove the default Windows PostgreSQL Server service registry entry
      if: ${{ env.pgWINServiceExists == 'true' }}
      shell: powershell
      run: |
        echo Removing registry entry
        Remove-Item -Path "HKLM:\SOFTWARE\PostgreSQL" -Recurse -Force
