
on: [push, pull_request]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Set the value
      shell: cmd
      run: |
        echo on
        echo  list of the human-readable names
        sc query state= all | find "DISPLAY_NAME"
