name: CI

# share data between jobs and store data once a workflow is complete

on: [push, pull_request, workflow_dispatch]

jobs:

  configure_remus:
    name: Make Remus Artifacts Job
    runs-on: ubuntu-latest

    steps:

    - name: Create "workspace" Artifact
      run: |
        mkdir                                         PGHOME
        echo REMUS_DATA  >                            PGHOME/remus.txt
        7z a -t7z -mmt24 -mx7 -r /tmp/remus.7z       PGHOME/*

    - name: Upload "workspace" Artifact
    - uses: actions/upload-artifact@v3
      with:
        name: workspace
        path: /tmp/remus.7z
